/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Catan;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import static java.lang.Integer.parseInt;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author Alex
 */
public class catanFrame extends javax.swing.JFrame {

    boardCanvas canvas;
    controlPanel ctrl;
    handPanel hand;
    CatanGame game;
    
    /**
     * Creates new form catanFrame
     */
    public catanFrame() {
        initComponents();
        setLayout(new BorderLayout(5,5));
        
        //initialize canvases
        setTitle("Legends of Catan");
        game = new CatanGame();
        canvas = new boardCanvas(game.getBoard());
        ctrl = new controlPanel(game);
        hand = new handPanel(game);
        
        //give access to everyone
        ctrl.setBoardCanvas(canvas);
        
        this.getContentPane().setBackground(Color.BLACK);
        addMouseListener(new clickRefresh(this, canvas));
        
        for(Tile t : game.getBoard().tiles) {
          tileObj z = new tileObj(t);
          addMouseListener(new tileMouseListener(z));
        }
        
        //add players
        boolean complete = false;
        int n = 0;
        while(complete==false) {
          try {
            String s = JOptionPane.showInputDialog(this, "How many players? (max 4)", null);
            n = parseInt(s);
            game.setPlayerNum(n);
            complete = true;
          }
          catch(Exception e) {           
          }
        }
        if(n==0) n=1;
        if(n<1) n=1;
        if(n>4) n=4;
        System.err.println("Num: " + n);
        
        for(Player p : game.getPlayers()) {
            String q = JOptionPane.showInputDialog(this, "Name?", null);
            p.setName(q);
        }
        try {
            hand.getRedName().setText(game.getPlayers().get(0).getName());
            System.err.println("1: " + game.getPlayers().get(0).getName());
        }
        catch(Exception e) {
        }
        try {
            hand.getWhiteName().setText(game.getPlayers().get(1).getName());
            System.err.println("2: " + game.getPlayers().get(1).getName());
        }
        catch(Exception e) {
        }
        try {
            hand.getOrangeName().setText(game.getPlayers().get(2).getName());
            System.err.println("3: " + game.getPlayers().get(2).getName());
        }
        catch(Exception e) {
        }
        try {
            hand.getBlueName().setText(game.getPlayers().get(3).getName());
            System.err.println("4: " + game.getPlayers().get(3).getName());
        }
        catch(Exception e) {
        }
        
        //initialize player stats
        hand.initializeStats();
        
        //add parts of the frame
        add(canvas);
        add(ctrl, BorderLayout.EAST);
        add(hand, BorderLayout.SOUTH);
        
        //add first pieces
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(catanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(catanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(catanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(catanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new catanFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
