/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Catan;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Elliot
 */
public class handPanel extends javax.swing.JPanel {

    private CatanGame game;
    
    /**
     * Creates new form handPanel
     */
    public handPanel(CatanGame theGame) {
        initComponents();
        game = theGame;
        setBackground(Color.BLACK);
        
        
    }
    
    public Icon getCardImage(String s) {
        ImageIcon wood = new ImageIcon("images/cards/wood.png");
        ImageIcon wheat = new ImageIcon("images/cards/wheat.png");
        ImageIcon sheep = new ImageIcon("images/cards/sheep.png");
        ImageIcon rock = new ImageIcon("images/cards/rock.png");
        ImageIcon brick = new ImageIcon("images/cards/brick.png");
        
        switch(s) {
            case "wood" : return wood;
            case "wheat" : return wheat;
            case "sheep" : return sheep;
            case "rock" : return rock;
            case "brick" : return brick;
            default : return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        redPanel = new javax.swing.JPanel();
        redNamePanel = new javax.swing.JPanel();
        redName = new javax.swing.JLabel();
        redCardPanel = new javax.swing.JPanel();
        redWood = new javax.swing.JLabel();
        redBrick = new javax.swing.JLabel();
        redSheep = new javax.swing.JLabel();
        redWheat = new javax.swing.JLabel();
        redRock = new javax.swing.JLabel();
        whitePanel = new javax.swing.JPanel();
        whiteNamePanel = new javax.swing.JPanel();
        whiteName = new javax.swing.JLabel();
        whiteCardPanel = new javax.swing.JPanel();
        whiteRock = new javax.swing.JLabel();
        whiteWheat = new javax.swing.JLabel();
        whiteSheep = new javax.swing.JLabel();
        whiteWood = new javax.swing.JLabel();
        whiteBrick = new javax.swing.JLabel();
        orangePanel = new javax.swing.JPanel();
        orangeNamePanel = new javax.swing.JPanel();
        orangeName = new javax.swing.JLabel();
        orangeCardPanel = new javax.swing.JPanel();
        orangeWood = new javax.swing.JLabel();
        orangeBrick = new javax.swing.JLabel();
        orangeSheep = new javax.swing.JLabel();
        orangeWheat = new javax.swing.JLabel();
        orangeRock = new javax.swing.JLabel();
        bluePanel = new javax.swing.JPanel();
        blueNamePanel = new javax.swing.JPanel();
        blueName = new javax.swing.JLabel();
        blueCardPanel = new javax.swing.JPanel();
        blueWood = new javax.swing.JLabel();
        blueBrick = new javax.swing.JLabel();
        blueSheep = new javax.swing.JLabel();
        blueWheat = new javax.swing.JLabel();
        blueRock = new javax.swing.JLabel();

        redPanel.setBackground(new java.awt.Color(255, 0, 0));
        redPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        redPanel.setPreferredSize(new java.awt.Dimension(196, 4));
        redPanel.setLayout(new javax.swing.BoxLayout(redPanel, javax.swing.BoxLayout.Y_AXIS));

        redNamePanel.setBackground(new java.awt.Color(204, 0, 0));
        redNamePanel.setPreferredSize(new java.awt.Dimension(196, 40));
        redNamePanel.setLayout(new javax.swing.BoxLayout(redNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        redName.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        redName.setText("name");
        redNamePanel.add(redName);

        redPanel.add(redNamePanel);

        redCardPanel.setBackground(java.awt.Color.red);
        redCardPanel.setLayout(new java.awt.GridLayout(5, 2));

        redWood.setForeground(new java.awt.Color(255, 255, 255));
        redCardPanel.add(redWood);

        redBrick.setForeground(new java.awt.Color(255, 255, 255));
        redCardPanel.add(redBrick);

        redSheep.setForeground(new java.awt.Color(255, 255, 255));
        redCardPanel.add(redSheep);

        redWheat.setForeground(new java.awt.Color(255, 255, 255));
        redCardPanel.add(redWheat);

        redRock.setForeground(new java.awt.Color(255, 255, 255));
        redCardPanel.add(redRock);

        redPanel.add(redCardPanel);

        whitePanel.setBackground(new java.awt.Color(255, 255, 255));
        whitePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        whitePanel.setPreferredSize(new java.awt.Dimension(196, 4));
        whitePanel.setLayout(new javax.swing.BoxLayout(whitePanel, javax.swing.BoxLayout.Y_AXIS));

        whiteNamePanel.setBackground(new java.awt.Color(204, 204, 204));
        whiteNamePanel.setPreferredSize(new java.awt.Dimension(196, 40));
        whiteNamePanel.setLayout(new javax.swing.BoxLayout(whiteNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        whiteName.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        whiteName.setText("name");
        whiteNamePanel.add(whiteName);

        whitePanel.add(whiteNamePanel);

        whiteCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        whiteCardPanel.setLayout(new java.awt.GridLayout(5, 1));
        whiteCardPanel.add(whiteRock);
        whiteCardPanel.add(whiteWheat);
        whiteCardPanel.add(whiteSheep);
        whiteCardPanel.add(whiteWood);
        whiteCardPanel.add(whiteBrick);

        whitePanel.add(whiteCardPanel);

        orangePanel.setBackground(java.awt.Color.orange);
        orangePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orangePanel.setPreferredSize(new java.awt.Dimension(196, 4));
        orangePanel.setLayout(new javax.swing.BoxLayout(orangePanel, javax.swing.BoxLayout.Y_AXIS));

        orangeNamePanel.setBackground(new java.awt.Color(255, 153, 0));
        orangeNamePanel.setPreferredSize(new java.awt.Dimension(196, 40));
        orangeNamePanel.setLayout(new javax.swing.BoxLayout(orangeNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        orangeName.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        orangeName.setText("name");
        orangeNamePanel.add(orangeName);

        orangePanel.add(orangeNamePanel);

        orangeCardPanel.setBackground(java.awt.Color.orange);
        orangeCardPanel.setLayout(new java.awt.GridLayout(5, 1));

        orangeWood.setForeground(new java.awt.Color(255, 255, 255));
        orangeCardPanel.add(orangeWood);

        orangeBrick.setForeground(new java.awt.Color(255, 255, 255));
        orangeCardPanel.add(orangeBrick);

        orangeSheep.setForeground(new java.awt.Color(255, 255, 255));
        orangeCardPanel.add(orangeSheep);

        orangeWheat.setForeground(new java.awt.Color(255, 255, 255));
        orangeCardPanel.add(orangeWheat);

        orangeRock.setForeground(new java.awt.Color(255, 255, 255));
        orangeCardPanel.add(orangeRock);

        orangePanel.add(orangeCardPanel);

        bluePanel.setBackground(java.awt.Color.blue);
        bluePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bluePanel.setPreferredSize(new java.awt.Dimension(196, 4));
        bluePanel.setLayout(new javax.swing.BoxLayout(bluePanel, javax.swing.BoxLayout.Y_AXIS));

        blueNamePanel.setBackground(new java.awt.Color(0, 0, 204));
        blueNamePanel.setPreferredSize(new java.awt.Dimension(196, 40));
        blueNamePanel.setLayout(new javax.swing.BoxLayout(blueNamePanel, javax.swing.BoxLayout.LINE_AXIS));

        blueName.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        blueName.setText("name");
        blueNamePanel.add(blueName);

        bluePanel.add(blueNamePanel);

        blueCardPanel.setBackground(java.awt.Color.blue);
        blueCardPanel.setLayout(new java.awt.GridLayout(5, 1));

        blueWood.setForeground(new java.awt.Color(255, 255, 255));
        blueCardPanel.add(blueWood);

        blueBrick.setForeground(new java.awt.Color(255, 255, 255));
        blueCardPanel.add(blueBrick);

        blueSheep.setForeground(new java.awt.Color(255, 255, 255));
        blueCardPanel.add(blueSheep);

        blueWheat.setForeground(new java.awt.Color(255, 255, 255));
        blueCardPanel.add(blueWheat);

        blueRock.setForeground(new java.awt.Color(255, 255, 255));
        blueCardPanel.add(blueRock);

        bluePanel.add(blueCardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(whitePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orangePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bluePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(redPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueBrick;
    private javax.swing.JPanel blueCardPanel;
    private javax.swing.JLabel blueName;
    private javax.swing.JPanel blueNamePanel;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JLabel blueRock;
    private javax.swing.JLabel blueSheep;
    private javax.swing.JLabel blueWheat;
    private javax.swing.JLabel blueWood;
    private javax.swing.JLabel orangeBrick;
    private javax.swing.JPanel orangeCardPanel;
    private javax.swing.JLabel orangeName;
    private javax.swing.JPanel orangeNamePanel;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JLabel orangeRock;
    private javax.swing.JLabel orangeSheep;
    private javax.swing.JLabel orangeWheat;
    private javax.swing.JLabel orangeWood;
    private javax.swing.JLabel redBrick;
    private javax.swing.JPanel redCardPanel;
    private javax.swing.JLabel redName;
    private javax.swing.JPanel redNamePanel;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel redRock;
    private javax.swing.JLabel redSheep;
    private javax.swing.JLabel redWheat;
    private javax.swing.JLabel redWood;
    private javax.swing.JLabel whiteBrick;
    private javax.swing.JPanel whiteCardPanel;
    private javax.swing.JLabel whiteName;
    private javax.swing.JPanel whiteNamePanel;
    private javax.swing.JPanel whitePanel;
    private javax.swing.JLabel whiteRock;
    private javax.swing.JLabel whiteSheep;
    private javax.swing.JLabel whiteWheat;
    private javax.swing.JLabel whiteWood;
    // End of variables declaration//GEN-END:variables

    public JLabel getBlueName() {
        return blueName;
    }

    public JLabel getOrangeName() {
        return orangeName;
    }

    public JLabel getRedName() {
        return redName;
    }

    public JLabel getWhiteName() {
        return whiteName;
    }
    
    public void initializeStats() {
        //make card images
        //red
        try {
          game.getPlayers().get(0);
          redWood.setIcon(getCardImage("wood"));
            redWood.setText("0");
          redWheat.setIcon(getCardImage("wheat"));
            redWheat.setText("0");
          redBrick.setIcon(getCardImage("brick"));
            redBrick.setText("0");
          redSheep.setIcon(getCardImage("sheep"));
            redSheep.setText("0");
          redRock.setIcon(getCardImage("rock"));
            redRock.setText("0");
        }
        catch(Exception e) {
            redName.setText("");
        }
          //white
        try {
          game.getPlayers().get(1);
          whiteWood.setIcon(getCardImage("wood"));
            whiteWood.setText("0");
          whiteWheat.setIcon(getCardImage("wheat"));
            whiteWheat.setText("0");
          whiteBrick.setIcon(getCardImage("brick"));
            whiteBrick.setText("0");
          whiteSheep.setIcon(getCardImage("sheep"));
            whiteSheep.setText("0");
          whiteRock.setIcon(getCardImage("rock"));
            whiteRock.setText("0");
        }
        catch(Exception e) {
            whiteName.setText("");
        }
        //blue
        try {
          game.getPlayers().get(3);
          blueWood.setIcon(getCardImage("wood"));
            blueWood.setText("0");
          blueWheat.setIcon(getCardImage("wheat"));
            blueWheat.setText("0");
          blueBrick.setIcon(getCardImage("brick"));
            blueBrick.setText("0");
          blueSheep.setIcon(getCardImage("sheep"));
            blueSheep.setText("0");
          blueRock.setIcon(getCardImage("rock"));
            blueRock.setText("0");
        }
        catch(Exception e) {
            blueName.setText("");
        }
        //orange
        try {
          game.getPlayers().get(2);
          orangeWood.setIcon(getCardImage("wood"));
            orangeWood.setText("0");
          orangeWheat.setIcon(getCardImage("wheat"));
            orangeWheat.setText("0");
          orangeBrick.setIcon(getCardImage("brick"));
            orangeBrick.setText("0");
          orangeSheep.setIcon(getCardImage("sheep"));
            orangeSheep.setText("0");
          orangeRock.setIcon(getCardImage("rock"));
            orangeRock.setText("0");
        }
        catch(Exception e) {
            orangeName.setText("");
        }
    }
}
